const fs = require('fs');
const path = require('path');

const PROCESSES_DIR = path.join(__dirname, '..', 'processes');

function validateStep(step, location) {
  if (!step.name) throw new Error(`${location} is missing "name"`);
  if (!step.owner) throw new Error(`${location} is missing "owner"`);
  if (!step.reason) throw new Error(`${location} is missing "reason"`);

  if (step.steps) {
    if (!Array.isArray(step.steps)) {
      throw new Error(`${location}.steps must be an array`);
    }
    step.steps.forEach((subStep, i) => {
      if (subStep.steps) {
        throw new Error(`${location}.steps[${i}] cannot have its own steps — one level deep only`);
      }
      validateStep(subStep, `${location}.steps[${i}]`);
    });
  }
}

function validateProcess(data) {
  if (!data.name) throw new Error('Process is missing "name"');
  if (!data.owner) throw new Error('Process is missing "owner"');
  if (!Array.isArray(data.inputs)) throw new Error('Process is missing "inputs" array');
  if (!Array.isArray(data.outputs)) throw new Error('Process is missing "outputs" array');
  if (!Array.isArray(data.steps)) throw new Error('Process is missing "steps" array');
  if (!Array.isArray(data.upstream)) throw new Error('Process is missing "upstream" array');
  if (!Array.isArray(data.downstream)) throw new Error('Process is missing "downstream" array');

  data.steps.forEach((step, i) => {
    validateStep(step, `steps[${i}]`);
  });
}

function readProcess(name) {
  const filePath = path.join(PROCESSES_DIR, name, 'process.json');

  if (!fs.existsSync(filePath)) {
    throw new Error(`No process found with name "${name}"`);
  }

  const raw = fs.readFileSync(filePath, 'utf8');
  const data = JSON.parse(raw);
  validateProcess(data);
  return data;
}

function writeTemplate(name, data) {
  const dir = path.join(PROCESSES_DIR, name);
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }

  fs.writeFileSync(path.join(dir, 'process.json'), JSON.stringify(data, null, 2));

  const mdPath = path.join(dir, 'process.md');
  if (!fs.existsSync(mdPath)) {
    fs.writeFileSync(mdPath, `# ${name}\n\n_Generated by ProcessBrain_\n`);
  }
}

function writeProcess(name, data) {
  validateProcess(data);

  const dir = path.join(PROCESSES_DIR, name);
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }

  fs.writeFileSync(path.join(dir, 'process.json'), JSON.stringify(data, null, 2));

  const mdPath = path.join(dir, 'process.md');
  if (!fs.existsSync(mdPath)) {
    fs.writeFileSync(mdPath, `# ${data.name}\n\n_Generated by ProcessBrain_\n`);
  }

  // Auto-regenerate gap report whenever a process file changes
  try {
    const { buildReport } = require('./renderer');
    buildReport();
  } catch (e) {
    // renderer not available yet — skip silently
  }
}

function listProcesses() {
  if (!fs.existsSync(PROCESSES_DIR)) return [];

  return fs.readdirSync(PROCESSES_DIR).filter(name => {
    return fs.existsSync(path.join(PROCESSES_DIR, name, 'process.json'));
  });
}

module.exports = { readProcess, writeTemplate, writeProcess, validateProcess, listProcesses };
